# Generated by Django 4.0.2 on 2022-04-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_remove_userprofile_id_remove_userprofile_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_master', models.CharField(default='Game Master', max_length=240)),
                ('group_name', models.CharField(max_length=240)),
                ('campaign', models.CharField(max_length=240)),
                ('group_size', models.CharField(max_length=240)),
                ('age_minimum', models.CharField(max_length=240)),
                ('experience_level', models.CharField(max_length=240)),
                ('meeting_frequencies', models.CharField(max_length=240)),
                ('group_description', models.CharField(max_length=240)),
                ('group_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PendingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('message_text', models.TextField()),
                ('time', models.TextField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='%(class)s_requests_created', through='core.PendingGroup', to='user.UserProfile'),
        ),
    ]
