# Generated by Django 4.0.2 on 2022-04-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_master', models.CharField(default='Game Master', max_length=240)),
                ('group_name', models.CharField(max_length=240)),
                ('campaign', models.CharField(max_length=240)),
                ('group_size', models.CharField(max_length=240)),
                ('age_minimum', models.CharField(max_length=240)),
                ('experience_level', models.CharField(max_length=240)),
                ('meeting_frequencies', models.CharField(max_length=240)),
                ('group_description', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('message_text', models.TextField()),
                ('time', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
        ),
    ]
