# Generated by Django 2.2.12 on 2022-04-06 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20220406_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_master', models.CharField(default='Game Master', max_length=240)),
                ('group_name', models.CharField(max_length=240)),
                ('campaign', models.CharField(max_length=240)),
                ('group_size', models.CharField(max_length=240)),
                ('age_minimum', models.CharField(max_length=240)),
                ('experience_level', models.CharField(max_length=240)),
                ('meeting_frequencies', models.CharField(max_length=240)),
                ('group_description', models.CharField(max_length=240)),
                ('group_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PendingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_requests_created', through='core.PendingGroup', to='user.UserProfile'),
        ),
    ]
