# Generated by Django 4.0.3 on 2022-05-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_notice_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='notice_board',
        ),
        migrations.AddField(
            model_name='group',
            name='schedule',
            field=models.CharField(default=0, max_length=240),
            preserve_default=False,
        ),
    ]
